config/routes.rb
Mywy::Application.routes.draw do
  mount API => '/'
  
  mount WeixinRailsMiddleware::Engine, at: "/"
  
  resources :foods, only: [:show, :index] do
    resources :comments
    resources :favorites, :only => [:create, :destroy]
  end

  resources :dinner_tables

  resources :restaurants do
    resources :favorites, :only => [:create, :destroy]
  end

  resources :events

  resources :trailers

  resources :tickets

  resources :cinemas, only: [:show] do
    resources :events
    resources :employments, only: [:index, :show, :create]
    resources :show_times do
      member do
        get :order
      end
    end
    resources :tickets
  end

  resources :movies do
    resources :comments
    resources :favorites, :only => [:create, :destroy]
  end
  resources :show_times
  resources :hall_seats
  resources :tickets, :only => [:index, :create]
  resources :favorites, :only => [:index]

  get "home/index"
  
  root 'home#index'

  resources :categories

  resources :orders do
    collection do
      post :alipay_notify
    end
    member do
      post :pay
    end
  end

  resources :carts, :only => [:index]

  resources :line_items

  resources :pictures

  resources :products, :only => [:index, :show] do
    resources :comments
    resources :favorites, :only => [:create, :destroy]
  end

  resources :nodes do
    resources :products, :only => [:index]
  end

  resources :members do
    collection do
      get :check_email
    end
  end

  devise_for :members, :path => "accounts", :controllers => {
    :sessions => :sessions,
    :registrations => :accounts
  }

  namespace :account do
    resources :addresses do
      member do
        get :set_ship_address
      end
    end
  end

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/accounts'
  }

  namespace :restaurant do
    resources :waps, only: [:show] do
      resources :foods, only: [:index, :show] do
        collection do
          get :search
        end
      end
    end
  end

  namespace :manage do
    namespace :cinema do
      resources :cinemas do
        resources :wechats do
          resources :waps, only: [:edit, :update]
          resources :wechat_texts
          resources :wechat_articles
          resources :diymenus
          member do
            get :authorize
            get :replyset
            get :focusset
          end
        end
        resources :events
        resources :employments, only: [:index, :update, :destroy]
        resources :movie_halls do
          resources :hall_seats
        end
        resources :show_times
        resources :tickets
      end
    end

    namespace :restaurant do
      resources :restaurants do
        resources :bills do
          member do
            get :checkout
          end
          resources :bill_items
        end
        resources :wechats do
          resources :waps, only: [:edit, :update]
          resources :wechat_texts
          resources :wechat_articles
          resources :diymenus do
            collection do
              get :generate_menu
            end
          end
          member do
            get :authorize
            get :replyset
            get :focusset
          end
        end
        resources :dinner_tables
        resources :events
        resources :employments, only: [:index, :update, :destroy]
        resources :foods do
          resources :images
        end
      end
    end
  end

  namespace :cpanel do
    root :to => "orders#index"

    resources :movies do
      resources :trailers
    end
    resources :cinemas do
      resources :movie_halls do
        resources :hall_seats
      end
      resources :show_times
    end
    resources :members

    resources :orders

    resources :carts

    resources :option_types do
      resources :option_values
    end

    resources :products do
      resources :pictures
      resources :variants
      resources :stock_items
      collection do
        get :search
      end
      member do
        get :categories
      end
    end

    resources :nodes do
      resources :products do
        resources :pictures
        resources :natures do
          collection do
            get :forming
          end
        end
      end
      resources :categories do
        collection do
          get :forming
        end
      end
    end
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
  extend Enumerize
  enumerize :business_scope, in: [:mywy, :restaurant], default: :mywy

  mount_uploader :avatar, ImageUploader

	has_many :categories, :dependent => :destroy
  has_many :products
  has_many :foods

  validates :name, presence: true
end

app/controllers/cpanel/nodes_controller.rb
class Cpanel::NodesController < Cpanel::ApplicationController
	before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to cpanel_nodes_path, notice: 'Node was successfully created.' }
        format.json { render action: 'show', status: :created, location: @node }
      else
        format.html { render action: 'new' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to cpanel_nodes_path, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to cpanel_nodes_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:name, :business_scope)
    end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.where("business_scope = 'mywy'")
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: '新节点保存成功！' }
        format.json { render action: 'show', status: :created, location: @node }
      else
        format.html { render action: 'new' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: '节点更新成功！' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:name)
    end
end

app/helpers/cpanel/nodes_helper.rb
module Cpanel::NodesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <%= render 'shared/form_error_messages', :f => f %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html+phone.slim
header.bar.bar-nav
  a.btn.pull-left
    = "客户端"
  a.btn.pull-right
    = "刷选"
  h1.title
    = "美月无忧"
nav.bar.bar-tab
  a href=root_path class="tab-item #{'active' if controller_name == 'waps' && action_name == 'show'}"
    span.icon.icon-home
    span.tab-label
      = "首页"
  a href=carts_path class="tab-item"
    span.icon.icon-gear
    span.tab-label
      = "购物车"
  a href=nodes_path class="tab-item"
    span.icon.icon-list
    span.tab-label
      = "分类"
  a href="#" class="tab-item #{'active' if controller_name == 'foods' && action_name == 'search'}"
    span.icon.icon-search
    span.tab-label
      = "搜索"
  a href=edit_member_registration_path class="tab-item"
    span.icon.icon-person
    span.tab-label
      = "我的"
.content
  ul.table-view
    - Node.where("business_scope = 'mywy'").each do |node|
      li.table-view-cell
        = link_to node.name, node_products_path(node)

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.name %></td>
        <td><%= link_to 'Show', node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>