config/routes.rb
Mywy::Application.routes.draw do
  mount API => '/'
  
  mount WeixinRailsMiddleware::Engine, at: "/"
  
  resources :foods, only: [:show, :index] do
    resources :comments
    resources :favorites, :only => [:create, :destroy]
  end

  resources :dinner_tables

  resources :restaurants do
    resources :favorites, :only => [:create, :destroy]
  end

  resources :events

  resources :trailers

  resources :tickets

  resources :cinemas, only: [:show] do
    resources :events
    resources :employments, only: [:index, :show, :create]
    resources :show_times do
      member do
        get :order
      end
    end
    resources :tickets
  end

  resources :movies do
    resources :comments
    resources :favorites, :only => [:create, :destroy]
  end
  resources :show_times
  resources :hall_seats
  resources :tickets, :only => [:index, :create]
  resources :favorites, :only => [:index]

  get "home/index"
  
  root 'home#index'

  resources :categories

  resources :orders do
    collection do
      post :alipay_notify
    end
    member do
      post :pay
    end
  end

  resources :carts, :only => [:index]

  resources :line_items

  resources :pictures

  resources :products, :only => [:index, :show] do
    resources :comments
    resources :favorites, :only => [:create, :destroy]
  end

  resources :nodes do
    resources :products, :only => [:index]
  end

  resources :members do
    collection do
      get :check_email
    end
  end

  devise_for :members, :path => "accounts", :controllers => {
    :sessions => :sessions,
    :registrations => :accounts
  }

  namespace :account do
    resources :addresses do
      member do
        get :set_ship_address
      end
    end
  end

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/accounts'
  }

  namespace :restaurant do
    resources :waps, only: [:show] do
      resources :foods, only: [:index, :show] do
        collection do
          get :search
        end
      end
    end
  end

  namespace :manage do
    namespace :cinema do
      resources :cinemas do
        resources :wechats do
          resources :waps, only: [:edit, :update]
          resources :wechat_texts
          resources :wechat_articles
          resources :diymenus
          member do
            get :authorize
            get :replyset
            get :focusset
          end
        end
        resources :events
        resources :employments, only: [:index, :update, :destroy]
        resources :movie_halls do
          resources :hall_seats
        end
        resources :show_times
        resources :tickets
      end
    end

    namespace :restaurant do
      resources :restaurants do
        resources :bills do
          member do
            get :checkout
          end
          resources :bill_items
        end
        resources :wechats do
          resources :waps, only: [:edit, :update]
          resources :wechat_texts
          resources :wechat_articles
          resources :diymenus do
            collection do
              get :generate_menu
            end
          end
          member do
            get :authorize
            get :replyset
            get :focusset
          end
        end
        resources :dinner_tables
        resources :events
        resources :employments, only: [:index, :update, :destroy]
        resources :foods do
          resources :images
        end
      end
    end
  end

  namespace :cpanel do
    root :to => "orders#index"

    resources :movies do
      resources :trailers
    end
    resources :cinemas do
      resources :movie_halls do
        resources :hall_seats
      end
      resources :show_times
    end
    resources :members

    resources :orders

    resources :carts

    resources :option_types do
      resources :option_values
    end

    resources :products do
      resources :pictures
      resources :variants
      resources :stock_items
      collection do
        get :search
      end
      member do
        get :categories
      end
    end

    resources :nodes do
      resources :products do
        resources :pictures
        resources :natures do
          collection do
            get :forming
          end
        end
      end
      resources :categories do
        collection do
          get :forming
        end
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html+phone.erb
<header class="bar bar-nav">
  <a class="btn pull-left">客户端</a>
  <a class="btn pull-right">分类</a>
  <h1 class="title">美月无忧</h1>
</header>
<nav class="bar bar-tab">
  <a href="<%= root_path %>" class="tab-item #{'active' if controller_name == 'waps' && action_name == 'show'}">
    <span class="icon icon-home"></span>
    <span class="tab-label">首页</span>
  </a>
  <a href="<%= carts_path %>" class="tab-item">
    <span class="icon icon-gear"></span>
    <span class="tab-label">购物车</span>
  </a>
  <a href="<%= nodes_path %>" class="tab-item">
    <span class="icon icon-list"></span>
    <span class="tab-label">分类</span>
  </a>
  <a href="#" class="tab-item #{'active' if controller_name == 'foods' && action_name == 'search'}">
    <span class="icon icon-search"></span>
    <span class="tab-label">搜索</span>
  </a>
  <a href="<%= edit_member_registration_path %>" class="tab-item">
    <span class="icon icon-person"></span>
    <span class="tab-label">我的</span>
  </a>
</nav>
<div class="content">
  <%= render 'shared/notification' %>
  <section id="home_page">
    <div class="container">
      <div class="row">
        <section class="col-xs-12">
          <div id="movie" class="ui-slide-box">
            <div class="ui-slide-control">
              <span class="title">商城</span>
            </div>
            <div class="ui-slide-content">
              <% Product.all.order("sales ASC").limit(4).each do |product| %>
                <div class="ui-slide-content-box">
                  <%= link_to product_path(product) do %>
                    <%= image_tag(product.pictures.first.image.url("140x140")) if not product.pictures.blank? %>
                  <% end %>
                  <div class="controll-box">
                    <a href="" class="left pull-left" alt="订票">
                      <span class="fa fa-plus"></span>
                    </a>
                    <a href="" class="right pull-right" alt="赞">
                      <span class="fa fa-heart"></span>
                    </a>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </section>
      </div>
      <div class="row">
        <section class="col-xs-12">
          <div id="movie" class="ui-slide-box">
            <div class="ui-slide-control">
              <span class="title">餐饮</span>
            </div>
            <div class="ui-slide-content">
              <div class="row">
                <% Food.all.order("name ASC").limit(4).each do |food| %>
                <div class="ui-slide-content-box">
                  <%= link_to food_path(food) do %>
                    <%= image_tag(food.images.first.image.url("140x140")) %>
                  <% end %>
                  <div class="controll-box">
                    <a href="" class="left pull-left" alt="订票">
                      <span class="fa fa-plus"></span>
                    </a>
                    <a href="" class="right pull-right" alt="赞">
                      <span class="fa fa-heart"></span>
                    </a>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </section>
      </div>
      <div class="row">
        <section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div id="movie" class="ui-slide-box">
            <div class="ui-slide-control">
              <span class="title">电影</span>
            </div>
            <div class="ui-slide-content">
              <div class="row">
                <% Movie.all.limit(4).each do |movie| %>
                <div class="ui-slide-content-box">
                  <%= link_to movie_path(movie) do %>
                    <%= image_tag(movie.cover.url("140x140")) %>
                  <% end %>
                  <div class="controll-box">
                    <a href="" class="left pull-left" alt="订票">
                      <span class="fa fa-plus"></span>
                    </a>
                    <a href="" class="right pull-right" alt="赞">
                      <span class="fa fa-heart"></span>
                    </a>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </section>
</div>

app/views/home/index.html.slim
#market-page
  .container
    nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          a.navbar-brand href="#"
            = "美月无忧"
        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          ul.nav.navbar-nav
            li class="active"
              = link_to "首页", root_path
            li
              = link_to "电影购票&影讯", movies_path
            li
              = link_to "愉快购物", products_path
            li
              = link_to "智能点餐", products_path
            li
              = link_to "尝试云购", products_path

= render 'shared/notification'

section#home_page
  .container
    .row
      .col-md-9
        .row
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            .box
              #market class="ui-slide-box"
                .box-products.slide
                  .ui-slide-control
                    span class="title"
                      = "最新上架"
                  .carousel-inner.ui-slide-content
                    .item.active.product-grid.no-margin.row
                      - Product.all.limit(8).order("created_at DESC").each do |product|
                        .products-item.col-lg-3
                          .item-thumb
                            = link_to product_path(product) do
                              = image_tag(product.pictures.first.image.url("500x500")) if not product.pictures.blank?
                          h3 class="item-name"
                            = link_to product.name, product_path(product)
                          .item-price
                            = "#{product.price} 元"
                          .item-action
                            = link_to product_path(product) do
                              i class="fa fa-plus-circle"
                              = " 加入购物车"
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            #food.ui-slide-box
              .ui-slide-control
                span.title
                  = "人气食品"
                .pull-right
                  a.prev-next-btn.left href="#" data-slide="prev"
                  a.prev-next-btn.right href="#" data-slide="next"
              .ui-slide-content
                .row
                  - Food.all.limit(5).order("created_at ASC").each do |food|
                    .ui-slide-content-box.col-md-3
                      = link_to food_path(food) do
                        = image_tag(food.images.first.image.url("140x140")) if not food.images.blank?
                      .controll-box style="height:60px;"
                        p.name
                          = link_to food_path(food) do
                            = food.name
                        p.price.text-danger
                          = "#{food.price} 元"
                      .controll-box
                        a href="#" class="left pull-left" alt="订餐" onclick="" data-id="#{food.id}"
                          span.fa.fa-plus
                        = favorite_heart_tag(food)
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            #movie.ui-slide-box
              .ui-slide-control
                span.title
                  = "电影"
                .pull-right
                  a.prev-next-btn.left href="#" data-slide="prev"
                  a.prev-next-btn.right href="#"  data-slide="next"
              .ui-slide-content
                .row
                  - Movie.all.limit(5).each do |movie|
                    .ui-slide-content-box.col-md-3
                      = link_to movie_path(movie) do
                        = image_tag(movie.cover.url("140x140"))
                      .controll-box
                        a href="" class="left pull-left" alt="订票"
                          span class="fa fa-plus"
                        a href="" class="right pull-right" alt="赞"
                          span class="fa fa-heart"
      
      .col-md-3
        .ui-slide-box
          .ui-slide-control
            span class="title"
              = "话费充值"
          .ui-slide-content
            form class="xm-recharge-form" action="#"
              fieldset class="xm-recharge-tel"
                label for="rechargeTel"
                  = "手机号："
                span id="rechargeTips" class="xm-recharge-tips"
                input type="tel" class="form-control" name="rechargeTel" id="rechargeTel" placeholder="支持移动、联通、电信"
              fieldset class="xm-recharge-amount clearfix"
                span class="fieldset-name"
                  = "面值："
                label
                  input type="radio" name="rechargeAmount" id="amount30" value="30"
                  = "30元"
                label
                  input type="radio" name="rechargeAmount" id="amount50" value="50"
                  = "50元"
                label
                  input type="radio" name="rechargeAmount" id="amount100" value="100" checked="true"
                  = "100元"
              fieldset class="xm-recharge-price clearfix"
                span class="fieldset-name"
                  = "价格："
                span id="rechargePrice" class="fieldset-text"
                  span
                    = "98.4"
                  = "元起"
              fieldset class="xm-recharge-submit"
                input id="rechargeBtn" class="btn btn-danger btn-recharge-submit disabled" type="submit" value="服务正在升级"
        #movie class="ui-slide-box"
          .ui-slide-control
            span class="title"
              = "特价商品"
          .ui-slide-content