config/routes.rb
Mywy::Application.routes.draw do
  mount API => '/'
  
  mount WeixinRailsMiddleware::Engine, at: "/"
  
  resources :foods, only: [:show, :index] do
    resources :comments
    resources :favorites, :only => [:create, :destroy]
  end

  resources :dinner_tables

  resources :restaurants do
    resources :favorites, :only => [:create, :destroy]
  end

  resources :events

  resources :trailers

  resources :tickets

  resources :cinemas, only: [:show] do
    resources :events
    resources :employments, only: [:index, :show, :create]
    resources :show_times do
      member do
        get :order
      end
    end
    resources :tickets
  end

  resources :movies do
    resources :comments
    resources :favorites, :only => [:create, :destroy]
  end
  resources :show_times
  resources :hall_seats
  resources :tickets, :only => [:index, :create]
  resources :favorites, :only => [:index]

  get "home/index"
  
  root 'home#index'

  resources :categories

  resources :orders do
    collection do
      post :alipay_notify
    end
    member do
      post :pay
    end
  end

  resources :carts, :only => [:index]

  resources :line_items

  resources :pictures

  resources :products, :only => [:index, :show] do
    resources :comments
    resources :favorites, :only => [:create, :destroy]
  end

  resources :nodes do
    resources :products, :only => [:index]
  end

  resources :members do
    collection do
      get :check_email
    end
  end

  devise_for :members, :path => "accounts", :controllers => {
    :sessions => :sessions,
    :registrations => :accounts
  }

  namespace :account do
    resources :addresses do
      member do
        get :set_ship_address
      end
    end
  end

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/accounts'
  }

  namespace :restaurant do
    resources :waps, only: [:show] do
      resources :foods, only: [:index, :show] do
        collection do
          get :search
        end
      end
    end
  end

  namespace :manage do
    namespace :cinema do
      resources :cinemas do
        resources :wechats do
          resources :waps, only: [:edit, :update]
          resources :wechat_texts
          resources :wechat_articles
          resources :diymenus
          member do
            get :authorize
            get :replyset
            get :focusset
          end
        end
        resources :events
        resources :employments, only: [:index, :update, :destroy]
        resources :movie_halls do
          resources :hall_seats
        end
        resources :show_times
        resources :tickets
      end
    end

    namespace :restaurant do
      resources :restaurants do
        resources :bills do
          member do
            get :checkout
          end
          resources :bill_items
        end
        resources :wechats do
          resources :waps, only: [:edit, :update]
          resources :wechat_texts
          resources :wechat_articles
          resources :diymenus do
            collection do
              get :generate_menu
            end
          end
          member do
            get :authorize
            get :replyset
            get :focusset
          end
        end
        resources :dinner_tables
        resources :events
        resources :employments, only: [:index, :update, :destroy]
        resources :foods do
          resources :images
        end
      end
    end
  end

  namespace :cpanel do
    root :to => "orders#index"

    resources :movies do
      resources :trailers
    end
    resources :cinemas do
      resources :movie_halls do
        resources :hall_seats
      end
      resources :show_times
    end
    resources :members

    resources :orders

    resources :carts

    resources :option_types do
      resources :option_values
    end

    resources :products do
      resources :pictures
      resources :variants
      resources :stock_items
      collection do
        get :search
      end
      member do
        get :categories
      end
    end

    resources :nodes do
      resources :products do
        resources :pictures
        resources :natures do
          collection do
            get :forming
          end
        end
      end
      resources :categories do
        collection do
          get :forming
        end
      end
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :require_member
  # GET /carts
  # GET /carts.json
  def index
    @line_items = current_member.line_items.where("order_id IS NULL")
  end

end

app/controllers/cpanel/carts_controller.rb
class Cpanel::CartsController < ApplicationController
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cpanel/carts_helper.rb
module Cpanel::CartsHelper
end

app/views/carts/index.html.erb
<section id="market-page">
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">美月无忧商城</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "首页", products_path %></li>
            <% Node.all.each do |node| %>
            <li>
              <%= link_to node.name, node_products_path(node) %>
            </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
</section>
<section id="cart" class="offcanvas-siderbars">
  <div class="container">
    <div class="row">
      <form action="<%= new_order_path %>" method="get" id="line_items_form">
        <section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div id="content" class="panel panel-default">
            <div class="panel-heading">
              购物车
            </div>
            <div class="panel-body">
              <% if @line_items.blank? %>
              <h2><span class="fa fa-notification"></span>对不起，在购物车里找不到任何商品！</h2>
              <p>你的购物车还是空的哟!赶快 <%= link_to "喂饱", root_path, :class=>"btn btn-danger" %> 它吧！</p>

              <div class="buttons">
                <div class="right">
                  <%= link_to "继续购物", root_path, :class=>"btn btn-info" %></div>
                </div>
              </div>
              <% else %>
              <table class="table table-hover table-bordered">
                <thead>
                  <tr>
                    <td style="width:30px;"><input type="checkbox" checked="true" /></td>
                    <td class="image">图片</td>
                    <td class="name">商品</td>
                    <td class="quantity" style="width:70px;">数量</td>
                    <td class="price" style="width:100px;">单价</td>
                    <td class="total" style="width:100px;">总价</td>
                    <td style="width:110px;"></td>
                  </tr>
                </thead>
                <tbody>
                  
                  <% @line_items.each do |line_item| %>
                    <tr id="line_item_<%= line_item.id %>">
                      <td style="width:30px;line-height:40px;text-align:center;">
                        <input type="checkbox" name="line_items[]" value="<%= line_item.id %>" checked="true" />
                      </td>
                      <td class="image" data-label="Image" style="width:100px;height:50px;">
                        <%= line_item_image_tag(line_item) %>
                      </td>
                      <td class="name" data-label="Product Name">
                        <%= line_item_a_tag(line_item) %>
                        <div class="cart-option">
                          <% if not line_item.variant.blank? %>
                            <% line_item.variant.option_values.each do |option_value| %>
                              <%= "#{option_value.option_type.presentation}:#{option_value.presentation} " %>
                            <% end %>
                          <% end %>
                        </div>
                        <small></small>
                      </td>
                      <td class="quantity" data-label="Quantity" style="vertical-align:middle;">
                        <input type="text" name="quantity" data-id="<%= line_item.id %>" value="<%= line_item.quantity %>" size="1" />
                      </td>
                      <td class="price" style="line-height:40px;">￥<%= line_item.product.price %></td>
                      <td class="total" style="line-height:40px;">￥<%= line_item.product.price * line_item.quantity %></td>
                      <td style="line-height:40px;">
                        <%= link_to "移出购物车", line_item_path(line_item.id), :remote => true, :method => :delete %>
                      </td>
                    </tr>
                  <% end %>
                  
                </tbody>
              </table>
              <div class="buttons">
                <div class="pull-right">
                  <input type="submit" class="btn btn-danger" value="结算" />
                </div>
                <div class="left">
                  <%= link_to "继续购物", products_path, :class=>"btn btn-info" %>
                </div>
              </div>
              <% end %>
            </div>   
          </div>
        </section>
      </form>
    </div>
  </div>
</section>
<script type="text/javascript">
$("input[name='quantity']").change(function(){
  id = $(this).data("id");
  quantity = $(this).val();
  $.ajax({
    url: "/line_items/" + id,
    type: "PUT",
    data: {
      line_item: {
        quantity: quantity
      }
    }
  });
});
</script>